/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'cwzeng' at '12/16/16 10:15 PM' with Gradle 2.14
 *
 * @author cwzeng, @date 12/16/16 10:15 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
