//import org.junit.Test;
//import static org.junit.Assert.*;
//
///*
// * This Java source file was auto generated by running 'gradle init --type java-library'
// * by 'cwzeng' at '12/16/16 10:15 PM' with Gradle 2.14
// *
// * @author cwzeng, @date 12/16/16 10:15 PM
// */
//public class LibraryTest {
//    @Test public void testSomeLibraryMethod() {
//        Library classUnderTest = new Library();
//        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
//    }
//}
